---
- name: Download Agent file
  get_url:
    url: "https://github.com/grafana/agent/releases/latest/download/agent-linux-{{ type[ansible_architecture] }}.zip"
    dest: "/tmp/agent-linux.zip"
    mode: '0644'

- name: Install unzip
  package:
    name: unzip
    state: present
  when: install_unzip|bool

- name: Unarchive Agent
  unarchive:
    src: "/tmp/agent-linux.zip"
    dest: "{{ agent_location }}"
    remote_src: yes
    mode: '0755'

- name: Create directory for Agent's config file
  file:
    state: directory
    recurse: yes
    path: "{{ config_location }}"
    mode: 0755

- name: Create Agent's config file
  template:
    src: "{{ grafana_agent_config_template }}"
    dest: "{{ config_location }}/agent-config.yaml"
    mode: 0644
    force: yes

- name: Create Systemd service
  block:
    - name: Template the new service file for Grafana agent
      template:
        src: "{{ grafana_agent_systemd_template }}"
        dest: "{{ systemd_service_folder }}/grafana-agent.service"
        mode: '0644'

    - name: Reload and start service Grafana agent
      service:
        name: grafana-agent
        state: restarted
        daemon_reload: yes
        enabled: yes

- name: Install Promtail
  include_tasks: "promtail.yml"
  when:
    - loki_user is defined
